Persistence des données du User connecté
azerpas/prescurity-dashboard pull request #10
Opened 2021-06-24 17:56 UTC by MartinLenaerts

@azerpas je te laisse check dans _app.tsx, je me suis inspiré du tuto

2021-06-24 18:50 UTC, MartinLenaerts commented
@hugocp9 , @azerpas , @Xihiems , @Amel-HUMAYUN . 
J'ai enfin réussi à sauvegarder le user dans l'app, une fois qu'il est connecté.
J'ai mis un exemple d'utilisation dans doctorDashboard, celui-ci peut être réutilisé dans n'importe qu'elle page de l'app

 ``` typescript
const UserContext = useContext(UserContext) 
console.log(UserContext)
```

```
{
  loggedIn: true
  user: User {
            _name: Jean,
            _refreshToken: "AGEhc0..."
            _uid:"sfdmfuhdsf..."
            _email:"jean.dupond@prescurity.fr"
           }
}
```

L'objet User est amené à changer d'attribut

2021-06-25 09:50 UTC, azerpas requested changes
Top, modifie les deux trois trucs et merge chef 👍

2021-06-25 09:50 UTC, azerpas commented on src/components/header/index.tsx
> +                    <Link href={"/"} style={{textDecoration:"inherit"}} >
Hm je crois que j'avais mis NextLink parce que justement ils ont un module fait pour améliorer l'UX https://nextjs.org/docs/api-reference/next/link

2021-06-25 09:50 UTC, azerpas commented on src/context/user.tsx
> +export function getContext() : boolean | IUserContext{
Elle sert à rien cette func no?

2021-06-25 09:50 UTC, azerpas commented on src/pages/index.tsx
> +           <Link href={"/doctorDashboard"}> <Button m={{base: "auto"}} ml={{base: "0"}} backgroundColor={{base: "black"}} color={{base: "white"}} fontWeight="bold">{props.button}</Button></Link>
Pareil, mets peut-être NextLink

2021-06-25 11:32 UTC, merged