Initialisation de la page Login
azerpas/prescurity-dashboard pull request #4
Opened 2021-06-15 08:45 UTC by Xihiems

Il manque un bouton dans le fichier form et il faut aussi travailler sur le visuel qui ne correspond pas totalement a la maquette.

2021-06-15 09:00 UTC, azerpas approved these changes
Nice, complète le form avec https://react-hook-form.com @Xihiems 🙂

2021-06-22 16:13 UTC, azerpas requested changes
Check les comments @MartinLenaerts (cc: @Xihiems  si ça t'intéresse)

2021-06-22 16:13 UTC, azerpas commented on src/components/form/index.tsx
> +
Ça on peut supp, c'est du duplicate

2021-06-22 16:13 UTC, azerpas commented on src/components/form/index.tsx
> +
TO REMOVE

2021-06-22 16:13 UTC, azerpas commented on src/pages/doctorDashboard.tsx
> +    )
TO REMOVE?

2021-06-22 16:20 UTC, MartinLenaerts commented on src/pages/doctorDashboard.tsx
> +    )
YES, je l'utilise dans login.tsx

2021-06-22 16:21 UTC, MartinLenaerts commented on src/components/form/index.tsx
> +
yes

2021-06-22 16:21 UTC, MartinLenaerts commented on src/components/form/index.tsx
> +
yes

2021-06-22 16:21 UTC, MartinLenaerts commented
en local j'ai déjà tout supprimé

2021-06-22 16:24 UTC, azerpas commented
> en local j'ai déjà tout supprimé

parfait merci 😁

2021-06-23 10:25 UTC, azerpas requested changes
On a deux trois trucs à modifier @MartinLenaerts , je te laisse check

2021-06-23 10:25 UTC, azerpas commented on package.json
> +    "react-async": "^10.0.1",
Plus besoin, @MartinLenaerts je te laisse delete?

2021-06-23 10:25 UTC, azerpas commented on src/components/form/index.tsx
> +    }
À reprendre en ASYNC/AWAIT

2021-06-23 10:25 UTC, azerpas commented on src/pages/doctorDashboard.tsx
> +
?

2021-06-23 10:25 UTC, azerpas commented on src/pages/login.tsx
> +    },[])
À améliorer (window property notamment)
Ajouter support de React-Hook-Form

2021-06-23 10:27 UTC, MartinLenaerts commented
Je regarde ça , j'essaye de tout rendre clean et on merge get aprem

2021-06-23 10:29 UTC, MartinLenaerts commented on src/pages/doctorDashboard.tsx
> +
Il y a pas la maquette figma, du coup je laisse en attente, mais c'est à faire sur la branche dashboardDoctor

2021-06-23 10:40 UTC, azerpas commented on src/pages/doctorDashboard.tsx
> +
Ok ok parfait 👍

2021-06-23 13:21 UTC, azerpas approved these changes

2021-06-23 13:26 UTC, azerpas reviewed
Je vais juste add react-hook-form

2021-06-23 14:16 UTC, MartinLenaerts approved these changes

2021-06-23 14:17 UTC, azerpas approved these changes

2021-06-23 14:18 UTC, azerpas commented
@MartinLenaerts je merge, on fait le reste (state de l'user dans l'app, etc...) dans une autre branche

2021-06-23 14:18 UTC, merged